name: Build qView for Windows Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release version (e.g., v4.0.1)'
        required: true
      prerelease:
        type: boolean
        description: 'Is this a pre-release?'
        required: false
        default: false

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - name: Set environment variables
        shell: bash
        run: |
          echo "qtArch=win64_msvc2022_64" >> $GITHUB_ENV
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          arch: 'win64_msvc2022_64'
          cache: true
          modules: 'qtimageformats'

      - name: Build qView
        shell: pwsh
        run: dist/scripts/build.ps1

      - name: Deploy qView
        shell: pwsh
        run: |
          Invoke-Expression "& 'dist/scripts/download-plugins.ps1'"
          Invoke-Expression "& 'dist/scripts/windeployqt.ps1' ${{ inputs.version }}"

      - name: Package for release
        shell: pwsh
        run: |
          $zipName = "qView-${{ inputs.version }}-Windows-x64.zip"
          Compress-Archive -Path bin\* -DestinationPath $zipName

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: qView ${{ inputs.version }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
          files: qView-${{ inputs.version }}-Windows-x64.zip
          body: |
            qView ${{ inputs.version }} for Windows x64
